global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'smeflow-api'
    static_configs:
      - targets: ['smeflow:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'flowise'
    static_configs:
      - targets: ['flowise:3000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 30s

  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']
    metrics_path: '/metrics'
    scrape_interval: 30s
